{"name": "Проверка неудачной авторизации с корявыми данными", "status": "passed", "steps": [{"name": "Логин существующего пользователя", "status": "passed", "parameters": [{"name": "user_data", "value": "{'email': '123123123', 'password': '123123123'}"}], "start": 1716205608624, "stop": 1716205608961}], "start": 1716205608624, "stop": 1716205608961, "uuid": "f23ccc42-b241-47db-ae01-acae0263a5c0", "historyId": "d27f5161b3ac0fb0c00ff6698956a1fb", "testCaseId": "d27f5161b3ac0fb0c00ff6698956a1fb", "fullName": "tests.test_user.TestUser#test_login_user_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUser"}, {"name": "host", "value": "debian"}, {"name": "thread", "value": "282076-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}